version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: restaurant-db
    ports:
      - "5432:5432" # Porta do Computador : Porta do Container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=restaurant_db
    restart: always